update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,11 +12,12 @@ jobs:
       - run:
           name: install shell-ignore-failure
           command: |
-            echo 'sh $@ || :' > /usr/local/bin/shell-ignore-failure
+            echo "#!/bin/sh -eo pipefail" > /usr/local/bin/shell-ignore-failure
+            echo 'sh $@ || :' >> /usr/local/bin/shell-ignore-failure
             chmod +x /usr/local/bin/shell-ignore-failure
       - run:
           name: ignore failure
-          shell: /usr/local/bin/shell-ignore-failure -eo pipefail
+          shell: /usr/local/bin/shell-ignore-failure # -eo pipefail
           command: |
             echo start
             false
