test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,7 +13,7 @@ jobs:
           name: install shell-ignore-failure
           command: |
             echo "#!/bin/sh" > /usr/local/bin/shell-ignore-failure
-            echo 'sh $@ || :' >> /usr/local/bin/shell-ignore-failure
+            echo 'sh || :' >> /usr/local/bin/shell-ignore-failure
             chmod +x /usr/local/bin/shell-ignore-failure
       - run:
           name: ignore failure
